using System;
namespace FileFormat.Words.Examples
{
    /// <summary>
    /// Provides C# code examples for creating, reading, and modifying Roman+Alphabetic paragraphs in DOCX
    /// using the <a href="https://www.nuget.org/packages/FileFormat.Words">FileFormat.Words</a> library.
    /// </summary>
    /// <example>
    /// <code>
    /// // Prepares directory Documents/Paragraph/RomanAlphabetic at the root of your project.
    /// // Check reference for more options and details.
    /// var paragraphRomanAlphabeticExamples = new ParagraphRomanAlphabeticExamples();
    /// // Creates a word document with paragraphs having roman and alphabetic levels and saves word
    /// // document to the specified directory. Check reference for more options and details.
    /// paragraphRomanAlphabeticExamples.CreateRomanAlphabeticParagraphs();
    /// // Reads Paragraphs from the specified Word Document and displays plain text with roman and alphabetic info.
    /// // Check reference for more options and details.
    /// paragraphRomanAlphabeticExamples.ReadRomanAlphabeticParagraphs();
    /// // Modifies Roman and Alphabetic paragraphs in the Word Document and saves the modified word document.
    /// // Check reference for more options and details.
    /// paragraphRomanAlphabeticExamples.ModifyRomanAlphabeticParagraphs();
    /// </code>
    /// </example>
    public class ParagraphRomanAlphabeticExamples
    {
        private const string docsDirectory = "../../../Documents/Paragraph/RomanAlphabetic";
        /// <summary>
        /// Initializes a new instance of the <see cref="ParagraphRomanAlphabeticExamples"/> class.
        /// Prepares the directory 'Documents/Paragraph/RomanAlphabetic' for storing or loading Word documents
        /// at the root of the project.
        /// If the directory doesn't exist, it is created. If it already exists,
        /// existing files are deleted, and the directory is cleaned up.
        /// </summary>
        public ParagraphRomanAlphabeticExamples()
        {
            if (!System.IO.Directory.Exists(docsDirectory))
            {
                // If it doesn't exist, create the directory
                System.IO.Directory.CreateDirectory(docsDirectory);
                System.Console.WriteLine($"Directory '{System.IO.Path.GetFullPath(docsDirectory)}' " +
                    $"created successfully.");
            }
            else
            {
                var files = System.IO.Directory.GetFiles(System.IO.Path.GetFullPath(docsDirectory));
                foreach (var file in files)
                {
                    System.IO.File.Delete(file);
                    System.Console.WriteLine($"File deleted: {file}");
                }
                System.Console.WriteLine($"Directory '{System.IO.Path.GetFullPath(docsDirectory)}' " +
                    $"cleaned up.");
            }
        }
        /// <summary>
        /// Creates a new Word Document with structured content using 
        /// <a href="https://www.nuget.org/packages/FileFormat.Words">FileFormat.Words</a>.
        /// Generates roman and alphabetic paragraphs with nested levels.
        /// Saves the newly created Word Document.
        /// </summary>
        /// <param name="documentDirectory">
        /// The directory where the Word Document will be saved (default is the 'Documents/Paragraph/RomanAlphabetic' directory auto-created at the root of your project).
        /// </param>
        /// <param name="filename">
        /// The name of the Word Document file (default is "WordParagraphsRomanAlphabetic.docx").
        /// </param>
        public void CreateRomanAlphabeticParagraphs(string documentDirectory = docsDirectory,
            string filename = "WordParagraphsRomanAlphabetic.docx")
        {
            try
            {
                // Create a document with roman and alphabeitc paragraphs using FileFormat.Words (https://www.nuget.org/packages/FileFormat.Words)

                // Initialize docx document
                FileFormat.Words.Document doc = new FileFormat.Words.Document();
                System.Console.WriteLine("Word Document with default template initialized");

                // Initialize document body
                var body = new FileFormat.Words.Body(doc);
                System.Console.WriteLine("Body of the Word Document initialized");

                // Initialize a paragraph
                var para = new FileFormat.Words.IElements.Paragraph();

                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "This document is generated by FileFormat.Words." });
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph();
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "Below are roman and alphabetic paragraphs:" });
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph { Style = "ListParagraph" };
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "First roman  at first level" });
                // Set roman numbering for the paragraph
                para.NumberingId = 1;
                para.IsRoman = true;
                para.NumberingLevel = 1;
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph { Style = "ListParagraph"};
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "First alphabetic at second level" });
                // Set alphabetic numbering for the paragraph
                para.NumberingId = 1;
                para.IsAlphabeticNumber = true;
                para.NumberingLevel = 2;
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph { Style = "ListParagraph"};
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "Second alphabetic at second level" });
                // Set alphabetic numbering for the paragraph
                para.NumberingId = 1;
                para.IsAlphabeticNumber = true;
                para.NumberingLevel = 2;
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph { Style = "ListParagraph" };
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "Second roman at first level" });
                // Set roman and indentation for the paragraph
                para.NumberingId = 1;
                para.IsRoman = true;
                para.NumberingLevel = 1;
                // Append paragraph to the document body
                body.AppendChild(para);

                // Reset paragraph
                para = new FileFormat.Words.IElements.Paragraph();
                // Add a run to paragraph
                para.AddRun(new FileFormat.Words.IElements.Run
                { Text = "The document ends here..." });
                // Append paragraph to the doucment body
                body.AppendChild(para);

                // Save docx document to the disk
                doc.Save($"{documentDirectory}/{filename}");
                System.Console.WriteLine($"Word Document {filename} Created. Please check directory: " +
                    $"{System.IO.Path.GetFullPath(documentDirectory)}");

                // The resulting docx document should be like this: https://imgur.com/d7ywVPG
            }
            catch (System.Exception ex)
            {
                throw new FileFormat.Words.FileFormatException("An error occurred.", ex);
            }
        }
        /// <summary>
        /// Loads a Word Document with structured content using 
        /// <a href="https://www.nuget.org/packages/FileFormat.Words">FileFormat.Words</a>.
        /// Traverses paragraphs and displays its text, roman/alphabetic status and level.
        /// </summary>
        /// <param name="documentDirectory">
        /// The directory where the Word Document to load is present
        /// (default is the 'Documents/Paragraph/RomanAlphabetic' directory auto-created at the root of your project).
        /// </param>
        /// <param name="filename">
        /// The name of the Word Document file to load (default is "WordParagraphsRomanAlphabetic.docx").
        /// </param>
        public void ReadRomanAlphabeticParagraphs(string documentDirectory = docsDirectory,
            string filename = "WordParagraphsRomanAlphabetic.docx")
        {
            try
            {
                // Load the Word Document
                var doc = new FileFormat.Words.Document($"{documentDirectory}/{filename}");

                // Initialize the body with the document
                var body = new FileFormat.Words.Body(doc);

                //System.Collections.Generic.List<FileFormat.Words.IElements.Paragraph>
                //  paragraphs = body.Paragraphs;

                var paragraphs = body.Paragraphs;

                foreach (FileFormat.Words.IElements.Paragraph paragraph in paragraphs)
                {
                    System.Console.WriteLine($"Paragraph Text : {paragraph.Text}");
                    System.Console.WriteLine($"Paragraph NumberingId : {paragraph.NumberingId}");
                    System.Console.WriteLine($"Paragraph Numbered? : {paragraph.IsNumbered}");
                    System.Console.WriteLine($"Paragraph Roman? : {paragraph.IsRoman}");
                    System.Console.WriteLine($"Paragraph AlphabeticNumber? : {paragraph.IsAlphabeticNumber}");
                    System.Console.WriteLine($"Paragraph Numbering Level : {paragraph.NumberingLevel}");
                }
            }
            catch (System.Exception ex)
            {
                throw new FileFormat.Words.FileFormatException("An error occurred.", ex);
            }
        }
        /// <summary>
        /// Loads a Word Document with structured content using 
        /// <a href="https://www.nuget.org/packages/FileFormat.Words">FileFormat.Words</a>.
        /// Traverses through all paragraphs within the document.
        /// If alphabetic, modifies paragraphs by appending ' (alphabetic removed)' with italic format
        /// and paragraph alphabetic is removed.
        /// Saves the modified Word Document.
        /// </summary>
        /// <param name="documentDirectory">
        /// The directory where the Word Document to load is present and
        /// the modified document will be saved (default is the 'Documents/Paragraph/RomanAlphabetic' directory auto-created at the root of your project).
        /// </param>
        /// <param name="filename">
        /// The name of the Word Document file to modify (default is "WordParagraphsRomanAlphabetic.docx").
        /// </param>
        /// <param name="filenameModified">
        /// The name of the modified Word Document (default is "ModifiedWordParagraphs.docx").
        /// </param>
        public void ModifyRomanAlphabeticParagraphs(string documentDirectory = docsDirectory,
            string filename = "WordParagraphsRomanAlphabetic.docx",
            string filenameModified = "ModifiedWordParagraphs.docx")
        {
            try
            {
                // Load the Word Document
                var doc = new FileFormat.Words.Document($"{documentDirectory}/{filename}");

                // Initialize the body with the document
                var body = new FileFormat.Words.Body(doc);

                //foreach (FileFormat.Words.IElements.Paragraph paragraph in body.Paragraphs)
                foreach (var paragraph in body.Paragraphs)
                {
                    if (paragraph.Style == "ListParagraph")
                    {
                        paragraph.Style = "Normal";
                        paragraph.AddRun(new FileFormat.Words.IElements.Run
                        { Text = " (alphabet removed)", Italic = true });
                        doc.Update(paragraph);
                    }
                }
                // Save the modified Word Document
                doc.Save($"{documentDirectory}/{filenameModified}");
                System.Console.WriteLine($"Word Document {filename} Modified and Saved As " +
                    $"{filenameModified}. Please check directory: " +
                    $"{System.IO.Path.GetFullPath(documentDirectory)}");
            }
            catch (System.Exception ex)
            {
                throw new FileFormat.Words.FileFormatException("An error occurred.", ex);
            }
        }
    }
}

